### ISSUE TITLE
Use initial expressions to select the initial value from a dropdown list populated using answer expressions

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1830]
**Is your feature request related to a problem? Please describe.**
When I populate a dropdown using the answer expression extension as per this [example](https://github.com/google/android-fhir/pull/1480#issue-1287687814), I cannot set the initial value using the initial expression extension. This is due to the item being of a reference type and the type I'm trying to populate is a string type. 

**Describe the solution you'd like**
I should be able to use initial expressions to set the initial value

**Describe alternatives you've considered**
Instead of using answer expressions, I can populate the dropdown with answer options instead but this is challenging where there are a large number of options.

**Additional context**
Here is the [questionnaire](https://github.com/google/android-fhir/files/10508042/initial.expressions.plus.answer.expressions.sample.questionnaire.txt) I tried and this is the [logcat](https://github.com/google/android-fhir/files/10508046/initial.expressions.plus.answer.expressions.log.cat.txt). If there is another way to do this, please point me in the right direction.

**Comment by omarismail94** [comment]
@KhumboLihonga  I can replicate your issue using the questionnaire I defined below, which works with  resources  fetched  from the public  `https://hapi.fhir.org/baseR4/` site.  

Will continue to debug


```
{
  "resourceType": "Questionnaire",
  "id": "test-questionnaire",
  "language": "en",
  "title": "Test Questionnaire",
  "status": "active",
  "publisher": "mcore",
  "contact": [
    {
      "name": "http://www.d-tree.org"
    }
  ],
  "item": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
          "valueCodeableConcept": {
            "coding": [
              {
                "system": "http://hl7.org/fhir/questionnaire-item-control",
                "code": "drop-down",
                "display": "Drop down"
              }
            ],
            "text": "Drop down"
          }
        },
        {
          "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression",
          "valueExpression": {
            "language": "text/fhirpath",
            "expression": "Patient.id"
          }
        },
        {
          "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-answerExpression",
          "valueExpression": {
            "expression": "Patient?address-city=NAIROBI",
            "language": "application/x-fhir-query"
          }
        },
        {
          "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-choiceColumn",
          "extension": [
            {
              "url": "path",
              "valueString": "name"
            },
            {
              "url": "label",
              "valueString": "name"
            },
            {
              "url": "forDisplay",
              "valueBoolean": true
            }
          ]
        }
      ],
      "linkId": "district",
      "text": "District",
      "type": "reference",
      "required": true
    }
  ]
}```

**Comment by omarismail94** [comment]
@KhumboLihonga I created PR #1831  to propose fixing. Please check out and lmk if you have any thoughts

**Comment by KhumboLihonga** [comment]
Hey @omarismail94, my colleague tested your PR and was unable to verify that the issue was fixed. This is the [comment ](https://github.com/google/android-fhir/pull/1831#issuecomment-1420673734) he left. Is there any update on this?

**Comment by omarismail94** [comment]
Hey @KhumboLihonga and @sevenreup , please see the attached video of the fix working:

Where is the app crashing for you, and what are the logs that you are getting?

I also had to implement the DataCaptureConfig.Provider interface in the FhirApplication class to provide an xFhirQueryResolver: 

https://github.com/google/android-fhir/pull/1831/files#diff-dc8902f9b4a0cb8dab12c5cdb57cfefbcf29b4482c5d2e28e60c6e51ac932389



https://user-images.githubusercontent.com/44980219/219350894-cb813ee7-06df-4044-b8b5-bfa101996320.mp4

**Comment by sevenreup** [comment]
@omarismail94 the initial expression is working when I use the example questionnaire you gave [here](https://github.com/google/android-fhir/issues/1830#issuecomment-1406810451), it only shows the resource reference as a label.
But when I try to change the label to something else for example the Patients name, it does not work. 
The questionnaire I am using is the one below.
```json
{
  "resourceType": "Questionnaire",
  "id": "test-questionnaire",
  "language": "en",
  "title": "Test Questionnaire",
  "status": "active",
  "publisher": "mcore",
  "contact": [
    {
      "name": "http://www.d-tree.org"
    }
  ],
  "item": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
          "valueCodeableConcept": {
            "coding": [
              {
                "system": "http://hl7.org/fhir/questionnaire-item-control",
                "code": "drop-down",
                "display": "Drop down"
              }
            ],
            "text": "Drop down"
          }
        },
        {
          "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression",
          "valueExpression": {
            "language": "text/fhirpath",
            "expression": "Patient.id"
          }
        },
        {
          "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-answerExpression",
          "valueExpression": {
            "expression": "Patient?address-city=NAIROBI",
            "language": "application/x-fhir-query"
          }
        },
        {
          "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-choiceColumn",
          "extension": [
            {
              "url": "path",
              "valueString": "name.given"
            },
            {
              "url": "label",
              "valueString": "text"
            },
            {
              "url": "forDisplay",
              "valueBoolean": true
            }
          ]
        }
      ],
      "linkId": "district",
      "text": "District",
      "type": "reference",
      "required": true
    }
  ]
}
```

**Comment by omarismail94** [comment]
@sevenreup hmm, is `name.given` a valid fhir path? can you try `name.first().given`? That should give you a list of all given names in the choices

**Comment by sevenreup** [comment]
It is a valid path. Even when I use `first()` I am still getting the same problem

**Comment by omarismail94** [comment]
When I do `name.first().given`, this is what I get:
![image](https://user-images.githubusercontent.com/44980219/220066337-374c2a0f-826f-48d0-aac1-54b89e01bc4c.png)

Is what you want that the Patient Id appears initially (not the given name), and then when the dropdown is selected, the given names are shown?

**Comment by sevenreup** [comment]
We want what we have defined as the `label` to appear initially and in the selection ( in this case, the patient's name). Because what is happening now is the initial selection is not working when you change the `path`.

**Comment by KhumboLihonga** [comment]
@omarismail94 I feel there are two issues here:
1. If the `path` attribute is changed to `name.first().given`, the dropdown options are indeed updated to display as intended BUT the initial expression does not set the initial value (regardless of how it is meant to be presented)
2. We should be able to define how the selected item should be presented using the `label` attribute

I believe point 1 is still a part of this PR while point 2 would be a separate PR. What do you think?

**Comment by KhumboLihonga** [comment]
@omarismail94 Just following up on this issue. What do you think about my comment above?

**Comment by KhumboLihonga** [comment]
@omarismail94 following up on this once again. Let me know your thoughts on the comment above so we can decide how to best proceed.
